-- MySQL Script generated by MySQL Workbench
-- Thu Dec 14 10:59:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_solvd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_solvd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_solvd` DEFAULT CHARACTER SET utf8 ;
USE `db_solvd` ;

-- -----------------------------------------------------
-- Table `db_solvd`.`phone_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_solvd`.`phone_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `phone_type_UNIQUE` (`type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_solvd`.`displays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_solvd`.`displays` (
  `id` INT NOT NULL,
  `inches_size` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_solvd`.`cameras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_solvd`.`cameras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resolution_MP` DOUBLE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_solvd`.`batteries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_solvd`.`batteries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `capacity_mAh` DOUBLE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_solvd`.`operating_systems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_solvd`.`operating_systems` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idoperating_systems_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_solvd`.`phones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_solvd`.`phones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `phone_types_id` INT NOT NULL,
  `displays_id` INT NOT NULL,
  `cameras_id` INT NOT NULL,
  `batteries_id` INT NOT NULL,
  `operating_systems_id` INT NOT NULL,
  PRIMARY KEY (`id`, `operating_systems_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_phones_phone_types1_idx` (`phone_types_id` ASC) VISIBLE,
  INDEX `fk_phones_displays1_idx` (`displays_id` ASC) VISIBLE,
  INDEX `fk_phones_cameras1_idx` (`cameras_id` ASC) VISIBLE,
  INDEX `fk_phones_batteries1_idx` (`batteries_id` ASC) VISIBLE,
  INDEX `fk_phones_operating_systems1_idx` (`operating_systems_id` ASC) VISIBLE,
  CONSTRAINT `fk_phones_phone_types1`
    FOREIGN KEY (`phone_types_id`)
    REFERENCES `db_solvd`.`phone_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phones_displays1`
    FOREIGN KEY (`displays_id`)
    REFERENCES `db_solvd`.`displays` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phones_cameras1`
    FOREIGN KEY (`cameras_id`)
    REFERENCES `db_solvd`.`cameras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phones_batteries1`
    FOREIGN KEY (`batteries_id`)
    REFERENCES `db_solvd`.`batteries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phones_operating_systems1`
    FOREIGN KEY (`operating_systems_id`)
    REFERENCES `db_solvd`.`operating_systems` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_solvd`.`contact_information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_solvd`.`contact_information` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `phone_number` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idtable1_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_solvd`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_solvd`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contact_information_id` INT NOT NULL,
  PRIMARY KEY (`id`, `contact_information_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_users_contact_information1_idx` (`contact_information_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_contact_information1`
    FOREIGN KEY (`contact_information_id`)
    REFERENCES `db_solvd`.`contact_information` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_solvd`.`users_has_phones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_solvd`.`users_has_phones` (
  `users_id` INT NOT NULL,
  `phones_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `phones_id`),
  INDEX `fk_users_has_phones_phones1_idx` (`phones_id` ASC) VISIBLE,
  INDEX `fk_users_has_phones_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_phones_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `db_solvd`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_phones_phones1`
    FOREIGN KEY (`phones_id`)
    REFERENCES `db_solvd`.`phones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_solvd`.`phone_accesories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_solvd`.`phone_accesories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_solvd`.`phones_has_phone_accesories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_solvd`.`phones_has_phone_accesories` (
  `phones_id` INT NOT NULL,
  `phone_accesories_id` INT NOT NULL,
  PRIMARY KEY (`phones_id`, `phone_accesories_id`),
  INDEX `fk_phones_has_phone_accesories_phone_accesories1_idx` (`phone_accesories_id` ASC) VISIBLE,
  INDEX `fk_phones_has_phone_accesories_phones1_idx` (`phones_id` ASC) VISIBLE,
  CONSTRAINT `fk_phones_has_phone_accesories_phones1`
    FOREIGN KEY (`phones_id`)
    REFERENCES `db_solvd`.`phones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phones_has_phone_accesories_phone_accesories1`
    FOREIGN KEY (`phone_accesories_id`)
    REFERENCES `db_solvd`.`phone_accesories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_solvd`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_solvd`.`contacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `phones_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  INDEX `fk_contacts_phones1_idx` (`phones_id` ASC) VISIBLE,
  CONSTRAINT `fk_contacts_phones1`
    FOREIGN KEY (`phones_id`)
    REFERENCES `db_solvd`.`phones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
